pages
sessionDescriptions
	^ HelpTopic 
		title: 'Session Descriptions'
		contents: 
'

	GsDevKit_home / ''sys'' / ''local'' / ''sessions'' / SCIGemStoneServerConfigSpec defaultSessionName

	GsDevKit_home / ''sys'' / ''local'' / ''sessions'' / ''Tugrik''

	TDSessionDescription {
		#name : ''Tugrik'',
		#stoneHost : ''foos'',
		#stoneName : ''Tugrik'',
		#gemHost : ''foos'',
		#netLDI : ''Tugrik_ldi'',
		#netLDIPort : '''',
		#gemTask : ''gemnetobject'',
		#userId : ''DataCurator'',
		#password : ''swordfish'',
		#osUserId : nil,
		#osPassword : nil,
		#dataDirectory : nil,
		#backupDirectory : ''/export/foos1/users/dhenrich/dev/_home/server/stones/Tugrik/backups/'',
		#snapshotDirectory : ''/export/foos1/users/dhenrich/dev/_home/server/stones/Tugrik/snapshots/'',
		#gemstoneVersion : ''3.3.0'',
		#gciLibraryName : nil,
		#adornmentColor : nil,
		#serverGitRoot : nil,
		#serverTodeRoot : ''/export/foos1/users/dhenrich/dev/_home'',
		#authorId : nil
	}

'